### ISSUE TITLE
Comment on: barbershop property

### ISSUE THREAD

**Issue by mesopelagique** [4d/docs#203]
- [properties_Scale.md](/4D/docs/blob/master/docs/FormObjects/properties_Scale.md)

Enter your comment here:
https://developer.4d.com/docs/en/FormObjects/propertiesScale.html#barber-shop
I think the properties is not `max` and a bool, it s a copy paste from other property

**Comment by arnaud4d** [comment]
C'est bien ça pourtant : si on passe "max" et un number = un barber shop, sinon = un thermometre simple

**Comment by mesopelagique** [comment]
I close but its not clear, not passed etc...
there is already a chapter after about "max" property

**Comment by arnaud4d** [comment]
comme dit dans la page https://developer.4d.com/docs/en/FormObjects/progressIndicator.html#barber-shop
"In JSON code, just remove "max" property from a default thermometer object to enable the Barber shop variant."
C'est le fonctionnement classique des json forms, l'absence d'une propriété crée un autre objet

**Comment by mesopelagique** [comment]
t'inquiete pas je comprend en lisant tout, c'est bien ca le soucis ;)
