### ISSUE TITLE
Comment on: BLOB

### ISSUE THREAD

**Issue by ArnaudDeMontard** [4d/docs#228]
- [dt_blob.md](/4D/docs/blob/master/docs/Concepts/dt_blob.md)

Hi doc team,
the example on how to distinguish scalar blob from 4D.Blob class doesn't return the expected True value, but False instead. I suppose it's because the test is made on an empty blob. See more here:
[https://discuss.4d.com/t/object-blob-property-byte-comparison-issue/21874/3?u=arnaud.de.montard](url)

**Comment by arnaud4d** [comment]
Hello, thank you for your report, we have fixed the docs!
