### ISSUE TITLE
Comment on: File get&set Text

### ISSUE THREAD

**Issue by mesopelagique** [4d/docs#231]
- [FileClass.md](/4D/docs/blob/master/docs/API/FileClass.md)

Enter your comment here:
 1- `""UTF-8"` in setText

2-in getText
```
... you get:

  // $Text = "id name price vat\r\n3 thé 1.06€\t19.6\r\n2\tcafé\t1.05€\t19.6"
  // \t = tab
  // \r = CR
```
I do not understand the block and why comment `//`
There is no $Text

so maybe
... you get for `$txt`:
```
"id name price vat\r\n3 thé 1.06€\t19.6\r\n2\tcafé\t1.05€\t19.6"
```
with `\t` a tabulation and \r the CR. line delimiter

3(not an error)-an example with optional parameters for getText?

**Comment by tony-b-4d** [comment]
Thanks Eric, we've fixed the typos and example according to your comments.

Tony
