### ISSUE TITLE
Comment on: Folder

### ISSUE THREAD

**Issue by mesopelagique** [4d/docs#232]
- [FolderClass.md](/4D/docs/blob/master/docs/API/FolderClass.md)

Enter your comment here:
In `4D.Folder` `files` or `4D.Folder` `folder` 
>  fk recursive | 1 | The collection contains files or folders of the specified folder and its subfolders
-- | -- | --

The collection contains files  (not folders)  for `4D.Folder` `files`
The collection contains folders  (not files)  for `4D.Folder` `folders`

but maybe it's due to doc generation and a common description of `fk recursive` constant at only one place

**Comment by arnaud4d** [comment]
Yes we use a single description for fk recursive constant but it come from the previous system; in this case we can have a more accurate description, we'll fix this thanks;
