### ISSUE TITLE
Comment on: On After Edit

### ISSUE THREAD

**Issue by jeremy-french-4D** [4d/docs#236]
- [onAfterEdit.md](/4D/docs/blob/Rx/docs/Events/onAfterEdit.md)

Enter your comment here:

I would like to suggest that the documentation be **revised** to indicate that the command ```Get edited text``` also works with the form event ```On After Edit```.

**Comment by arnaud4d** [comment]
Thank you for your suggestion, we have added a specific reference to Get editet text in that page,
