### ISSUE TITLE
Comment on: Managing 4D Licenses

### ISSUE THREAD

**Issue by DAP-GitHub** [4d/docs#237]
- [licenses.md](/4D/docs/blob/master/docs/Admin/licenses.md)

Enter your comment here:
I am trying to read the license. Arriving on th home page of the 4D site, no way to find my way. I finally got by chance on the development page : no mention of license; the Documentation button, then Managing your license.
Interesting : this page, as far as I can see, contains no link to the text iteslf of the licenses
There must be a better user friendly ergonomy, I guess
Dominique Poulain

**Comment by arnaud4d** [comment]
Access to the 4D product license text is provided at the bottom of every page of the 4D web site and documentation web site ("Product license" link) and also in the About page of 4D applications ("Legal information"). The "Managing 4D licences" page of the documentation explains how to register key files in the application, which is a very different topic. However we need to update links on the doc web site (v18-> v19). Thanks!
