### ISSUE TITLE
Comment on: DataClass: .exposed is not a property of a dataclass

### ISSUE THREAD

**Issue by macMikey** [4d/docs#240]
- [DataClassClass.md](https://developer.4d.com/docs/en/API/DataClassClass.html)

**.exposed** is not a standalone property of a dataclass
It is a sub-property of **getInfo**
```4d
myDataClass.exposed
```
returns an error
```4d
mydataClass.GetInfo().exposed
```
returns a boolean

Both the *summary* and the description should be updated.

**Comment by arnaud4d** [comment]
Thank you, it has been fixed
