### ISSUE TITLE
Comment on: Documentation updates

### ISSUE THREAD

**Issue by jeremy-french-4D** [4d/docs#241]
- [updates.md](/4D/docs/blob/Rx/docs/Notes/updates.md)

**Alias Attributes: LINK FAILS TO WORK**

I click "Alias Attributes". (See the red arrow in image #1.)

<img width="1899" alt="image" src="https://user-images.githubusercontent.com/53099470/164796833-794ec1b3-cd9c-4800-b818-ac6e178326cd.png">

A new page opens, and I see "Alias Attributes."

But the examples shown appear to deal with **Entity Class**, not Alias Attributes. And the sidebar shows **Entity Class** highlighted.

Clicking the link "Alias Attributes" **fails** to move to the "Alias Attributes" section. (See the red arrows in image #2.)

<img width="1899" alt="image" src="https://user-images.githubusercontent.com/53099470/164858478-f2278f84-4aca-47bd-b954-4390b0d67442.png">

Here's the actual "Alias Attribute" section, which is further down the documentation page. (See image #3 and red arrow.)

<img width="1899" alt="image" src="https://user-images.githubusercontent.com/53099470/164860427-e50198fd-5da1-4286-8a6c-441ebe140bbc.png">

**Comment by arnaud4d** [comment]
thanks, it now goes to the correct location
