### ISSUE TITLE
Comment on: Getting Started

### ISSUE THREAD

**Issue by jeremy-french-4D** [4d/docs#243]
- [getting-started.md](/4D/docs/blob/master/docs/ViewPro/getting-started.md)

Enter your comment here:

**Comment by jeremy-french-4D** [comment]
The first line reads:
>4D View Pro is a [4D component](https://developer.4d.com/docs/en/Concepts/components.html) that includes a [4D form area](https://developer.4d.com/docs/en/FormObjects/viewProAreaOverview.html) an specific [methods](https://developer.4d.com/docs/en/ViewPro/method-list.html).

Replace the determiner **an** with the conjunction **and**.

The revision will make the first line appear as:
>4D View Pro is a [4D component](https://developer.4d.com/docs/en/Concepts/components.html) that includes a [4D form area](https://developer.4d.com/docs/en/FormObjects/viewProAreaOverview.html) and specific [methods](https://developer.4d.com/docs/en/ViewPro/method-list.html).

Note that **an** now reads **and**.

**Comment by arnaud4d** [comment]
thank you, it is now fixed in all branches
