### ISSUE TITLE
Comment on: EntitySelection

### ISSUE THREAD

**Issue by macMikey** [4d/docs#246]
- [EntitySelectionClass.md](/4D/docs/blob/master/docs/API/EntitySelectionClass.md)

Enter your comment here:
Link to **toCollection** is wrong.
It's set to `https://developer.4d.com/docs/en/API/EntitySelectionClass.html#tocollection`
It should be `https://developer.4d.com/docs/en/API/EntitySelectionClass.html#tocollection-`

**Comment by arnaud4d** [comment]
thanks, we have fixed the page
