### ISSUE TITLE
Comment on: Éditeur de code

### ISSUE THREAD

**Issue by mtroya** [4d/docs#249]
- [write-class-method.md](/4D/docs/blob/master/docs/code-editor/write-class-method.md)
- 🇫🇷 [write-class-method.md](/4D/docs/blob/master/website/translated_docs/fr/code-editor/write-class-method.md)

Enter your comment here:
Est-ce normal qu'en sélectionnant la langue FRANCAIS seuls les titres de chapitre soient en français et tout le texte détaillé en anglais ? 

![image](https://user-images.githubusercontent.com/8439123/181727795-a2639174-75bf-4243-91c2-16f7d882aa55.png)

**Comment by arnaud4d** [comment]
Cet état indique que la page n'a pas encore été traduite en français. La traduction française est maintenant effectuée à 85% sur l'ensemble de developer.4d.com, nous travaillons quotidiennement à augmenter ce pourcentage et espérons pouvoir proposer l'ensemble du site traduit dans les semaines qui viennent. Désolé pour cette attente.
