### ISSUE TITLE
Comment on FormObjects/progressIndicator.md (19-R8)

### ISSUE THREAD

**Issue by IngoWolf** [4d/docs#283]
`1 (or any value other than 0) = Start animation`
Animation for barber pole and spinner starts only at value 1. Other positive or negative values don't start the animation. Tested in 4D v19R6 on Windows. Please fix or update documentation.

**Comment by arnaud4d** [comment]
You're right, animation only starts with value 1. Docs have been fixed, they will be online very soon.
Thanks for reporting!
The documentation team
