### ISSUE TITLE
Comment on API/FileClass.md (20) 🇫🇷: wrong trad

### ISSUE THREAD

**Issue by e-marchand** [4d/docs#290]
see https://discuss.4d.com/t/file-delete-la-documentation-se-prend-les-pieds-dans-le-tapis/27966

> Si le fichier existe déjà sur disque, la fonction ne fait rien (aucune erreur n’est générée).

> If the file does not exist on disk, the function does nothing (no error is generated).

**Comment by arnaud4d** [comment]
Fixed and published: https://developer.4d.com/docs/fr/API/FileClass/#delete

The broken syntax table will be fixed later
