### ISSUE TITLE
Comment on Admin/data-collect.md (20-R2)

### ISSUE THREAD

**Issue by ReesyGit** [4d/docs#296]
ServerDataCollection hyperlink to https://doc.4d.com/4Dv19R6/4D/19-R6/ServerDataCollection.300-6011712.en.html goes to a 404 page.

**Comment by arnaud4d** [comment]
Hello, thanks for reporting. It's fixed, will be online very soon. The correct link is: https://doc.4d.com/4Dv20/4D/20/ServerDataCollection.300-6335775.en.html
