### ISSUE TITLE
Comment on API/CollectionClass.md (20-R3) : example comment 

### ISSUE THREAD

**Issue by e-marchand** [4d/docs#313]
Please enter your comment:

https://developer.4d.com/docs/API/CollectionClass/#example-3-4

```4d
//["Alain Martin","Jane Doe","John Smith","John Doe"]
//["Lyon France","Eching Germany","Paris France","Berlin Germany"]
```

must be someting like that

```4d
//$name=["Alain Martin","Jane Doe","John Smith","John Doe"]
//$address=["Lyon France","Eching Germany","Paris France","Berlin Germany"]
```

but not really, $address contains object, not string? maybe exemple not correct

I launch it and have some errors "compare function doesn't provide consistent results"

**Comment by arnaud4d** [comment]
ok it's fixed thanks!
Correct code is $name.multiSort(Formula($1.value.firstname<$1.value2.firstname); **[$address]**)
