### ISSUE TITLE
Comment on WebServer/qodly-studio.md (20-R3)

### ISSUE THREAD

**Issue by mathieu-ferry** [4d/docs#316]
Qodly Studio can be used offline.
But we could comment that a couple of features are not available in Qodly Studio for 4D without an internet access:
* Templates: the template library will be empty withou internet connection
* UI tips

**Comment by arnaud4d** [comment]
I added this paragraph:
https://doc4d.github.io/docs/WebServer/qodly-studio/#offline-use
