### ISSUE TITLE
Comment on Debugging/debugLogFiles.md : cosntant for log level to expose

### ISSUE THREAD

**Issue by e-marchand** [4d/docs#319]
Please enter your comment:

in diagnostic log level
https://doc4d.github.io/docs/fr/next/Debugging/debugLogFiles/#activation-du-fichier
en : https://doc4d.github.io/docs/next/Debugging/debugLogFiles/#diagnostic-log-levels

there is a table for level, but contains WARN, ERROR, etc...
there is no code example so do be able to use it I have to found the constants, a blogpost using google show me the values

I think real constant name must be used ie. *Log warn* , and maybe an exemple
`SET DATABASE PARAMETER(Diagnostic log level; Log warn)`

**Comment by arnaud4d** [comment]
Done, thanks
