### ISSUE TITLE
wrong exemple for VP get value 

### ISSUE THREAD

**Issue by e-marchand** [4d/docs#326]
on VP SET TEXT VALUE line
https://github.com/4d/docs/blob/f5a1814edf6fbaee96d8c1b1c50a73559f472bd2/docs/ViewPro/method-list.md?plain=1#L2903

seems to take text, not object https://developer.4d.com/docs/ViewPro/method-list/#vp-set-text-value

maybe want to use vp set value https://developer.4d.com/docs/ViewPro/method-list/#vp-set-value

**Comment by arnaud4d** [comment]
Fixed example (parenthesis and VP SET VALUE) thanks
