### ISSUE TITLE
Comment on Concepts/quick-tour.md (20-R4)

### ISSUE THREAD

**Issue by JodyBevan** [4d/docs#337]
Please enter your comment: just a request for others, after I have now found this in the manuals.

I just spend an hour trying to find in the manual how to enter a carriage return in code text string, instead of using Char(Carriage return). 

I used the search using 'Carriage Return' and Char(carriage return).  Sure items came up, but not for doing what I know is available in 4D, but I could not remember the exact characters.

I then looked for Code Editor and that was explaining the features of the code editor. Certainly a good chapter to read (as are all the chapters).

In this I came across Escape sequence. It seemed this might be it. I clicked on the line - Jackpot hit - this was it. Now I know the 5 of them. 

My suggestion is to index Each of:
Line feed
Tab
Carriage return
Backslash
Quotation marks

in the nice table.

**Comment by arnaud4d** [comment]
Hello, thanks for your comment.
We have modified our indexing tool and you should now find such information more easily on developer.4d.com
Regards,

**Comment by JodyBevan** [comment]
Arnaud:

Tried it out. Great that brought it right up. Thanks.


Jody Bevan

￼
