### ISSUE TITLE
Comment on Concepts/paths.md (20-R5)

### ISSUE THREAD

**Issue by JodyBevan** [4d/docs#344]
First let me start off, by saying I am liking the greater detail in the new manual. Having spend many years plowing through the manuals from v2.0.10 ~1988 on, I do get used to each new format when that happens and I know it is hard to get used to the new format. One's brain gets used to knowing exactly where to look for specific types of information. I need more time using only the new manuals.

Possibly this comment is 'just me', but I will pass it along for your consideration.

When the new File / Folder object commands came out I was eager to use them because of all the extra automatically included information they would provide. I struggled with the commands though for more than a few months, before I got to use them. Having to get code done, one cannot spend too much time learning new commands. Go back to the old code that worked.

After struggling for some time, I smacked my head when I realized the results from these came back as an object. I looked at the documentation and would see in the examples that they results were returned into a local variable that gave no hint as to it's type. Sure it seems stupid to me know, but that is what caused me to stumble with utilizing the commands.

I find that in the examples the examples do not indicate the type of these local variables. I for one would find this very helpful if the digital ink could be 'wasted' on other, and embraced by the likes of me if in the examples, that the local variables indicated their type (typically using the compiler directives C_Object, var $File : Object

Thanks for your consideration.

**Comment by arnaud4d** [comment]
Hello,
Thanks for sharing your experience of the 4D language and its documentation, we pay high attention to returns from our users. You're right, the 'pathnames' section examples lack of variable type declarations that could help understanding the concepts and how to write 4D code. Throughout the documentation we try to always declare variables but some pages could miss them.
We fixed this page and added declarations for File and Folder object. Hopefully you can dive without reluctance in this programming style. Thanks, The documentation team
