### ISSUE TITLE
Mistake on settings/web.md (20-R6)

### ISSUE THREAD

**Issue by macMikey** [4d/docs#353]
toward the bottom, there is [a blog post link](https://blog.4d.com/force-login-now-is-the-default-mode-for-all-rest-authentications). i have marked the link with a pink square. the link is broken.

<img width="615" alt="Screenshot 2024-07-16 at 15 54 38" src="https://github.com/user-attachments/assets/723ee0b7-bc52-471e-b859-c055df7a8ac2">

**Comment by arnaud4d** [comment]
thanks, the link has been fixed. Sorry for the trouble.
