### ISSUE TITLE
Comment on ORDA/glossary.md (20-R5)

### ISSUE THREAD

**Issue by jeremy-french-4D** [4d/docs#359]
A **link** on a page to go to another part of the **same** page **fails**. It is a link with a fragment identifier (e.g., "**#**").

In the **20R5 documentation**, please go to the ORDA Glossary page.

https://developer.4d.com/docs/20-R5/ORDA/glossary

Scroll down to the term `AttributePath`.

<img width="827" alt="image" src="https://github.com/user-attachments/assets/c037d26a-cf8d-4e3e-9a4f-88c260250b35">

Notice that `PropertyPath` is a hypertext link. 

The hypertext link's code is:

```html
<a href="/docs/20-R5/ORDA/glossary/#propertyPath">PropertyPath</a>
```

But **clicking the link does nothing**. The page needs to scroll down to the `PropertyPath` term.

Also, note that the above hypertext link needs to include the class `hash_link`.

----

Now, manually scroll down the page `PropertyPath` term.

Click the term's **direct link**. The link **works**, and the PropertyPath is positioned at the top of the page.

The **direct link** code is: 
```4d
<a class="hash-link" aria-label="Direct link to heading" title="Direct link to heading" href="/docs/20-R5/ORDA/glossary/#propertypath"></a>
```

The direct link that **works** has a **class** named `hash-link`, which needs to be **added to the link that fails**.

**Comment by arnaud4d** [comment]
thanks Jeremy, a fix has been done the link should be ok now

**Comment by jeremy-french-4D** [comment]
Hi Arnaud,

I just tried the link, and nothing happened. The page fails to move down to the `PropertyPath` term.

Also, the `hash_link` class is absent from the link definition. See #3 following.

<img width="813" alt="image" src="https://github.com/user-attachments/assets/4c65811e-5096-439c-8835-656e8ed1c6e8">


-----


The following image shows my cursor **after clicking** the link (**#1**) and the URL in the **address bar** (**#2)**. But the glossary entry of `PropertyPath` doesn't appear. The page remains where I clicked the link.

<img width="1812" alt="image" src="https://github.com/user-attachments/assets/abb6c435-c5a3-4589-a25c-19d1adf1432a">

**Comment by arnaud4d** [comment]
Sorry, there is a delay for updating the web site and it is taking longer than usual. You might have to wait until tomorrow for the fix to be online.
